/**************************

This class is automatically generated by KFDataTool

***********************/
\#include "${CLASS}.h"
#for $group in $groups 
\#include "Any${group.group}.h"
#end for

namespace ${NS}
{
    void ${CLASS}::RegistAll()
    {
      #for $group in $groups
        Any${group.group}::Regist();
      #end for
    }
}
