/**************************

This class is automatically generated by KFDataTool

***********************/


\#pragma once


\#include "Format/KFDataFormat.h"
\#include "${CLASS}F.h"

namespace ${NS}
{
    class KFENGINERT_API ${CLASS}TypeDef
    {
#if $DEF_ENUM
    public:
     enum ${CLASS}TypeEnum
     {
        UNDEFINED = 0,
    #if $USECLSID 
        #for $kfd in $data.kfddatas 
        KF_ST_ENUM_${kfd.class} = ${kfd.clsid},
        #end for
    #else
        #for $kfd in $data.kfddatas 
        KF_ST_ENUM_${kfd.class} = ${kfd.typeid},
        #end for
    #end if
    };
#end if

    public:
        static ${CLASS}* Create(uint32 keytype);
        static ${CLASS}* Read(KFByteArray& buffarr,${CLASS}* obj = nullptr);
        static void Write(KFByteArray& buffarr,${CLASS}* obj);
        static kfMap<kfstr,int32> KeyTypes;
    };
}
