/**************************

This class is automatically generated by KFDataTool

***********************/


\#pragma once

#for $includestr in $data.includes 
\#include "${includestr}"
#end for

namespace ${NS}
{






    namespace KFENGINERT_API ${CLASS}_method
    {

    };
}
