/**************************

This class is automatically generated by KFDataTool

***********************/
\#pragma once
\#include "Utils/KFDefine.h"
#if $export_api==""
	#set $export_api="KFENGINERT_API"
#end if

namespace ${NS}
{
    class $export_api ${CLASS}
    {
    public:
    	static void RegistAll();
    };

}
