/**************************

This class is automatically generated by KFDataTool

***********************/


\#pragma once

#for $includestr in $data.includes 
\#include "${includestr}"
#end for

namespace ${NS}
{
	class KFENGINERT_API KFScriptManagerBase_Execute
    {
	public:
		 ~KFScriptManagerBase_Execute() 
		{
			kfDel(scriptData);
			kfDel(context);
		}
	public:

		KFScriptData* scriptData = NULL;
		KFScriptContext* context = NULL;

	public:
		void Call(void* ref_this = NULL)
		{
			if (ref_this != NULL)
			{
				auto this_object = (KFScriptManagerBase*)ref_this;
				this_object->Execute(scriptData, context);
			}
		}
    };
}
